- name: Jalankan Aksi Berdasarkan Event
  hosts: all
  become: true
  vars_files:
    - vars.yml

  vars: # ini ditulis di cli, bakal manggil tasks di bawah
    ssh_log: "{{ 'ssh_log' in event }}"
    ssh_command: "{{ 'ssh_command' in event }}"
    email: "{{ 'email' in event }}"
    api: "{{ 'api' in event }}"
    disaster_1: "{{ 'disaster A' in event}}"

  tasks:
    - name: INDIVIDUAL TASK - tulis Log over SSH
      include_tasks: actions/ssh_log.yml
      when: ssh_log

    - name: INDIVIDUAL TASK - do command over SSH
      include_tasks: actions/ssh_command.yml
      when: ssh_command

    - name: INDIVIDUAL TASK - kirim email
      include_tasks: actions/email.yml
      when: email

    - name: INDIVIDUAL TASK - do API call
      include_tasks: actions/api.yml
      when: api

    - name: Handle Disaster A
      loop:
        - actions/ssh_log.yml
        - actions/ssh_command.yml
      include_tasks: "{{ item }}"
      when: disaster_1
