- name: Lakukan API Call
  hosts: all
  tasks:
  - name: Make POST request with dynamic body
    uri:
      url: "{{ post_url }}"
      method: POST
      headers:
        Content-Type: "application/json"
      body: "{{ post_body }}"
      body_format: json
      status_code: 200
    register: http_response
    tags: api_call
    
  - name: Show HTTP response
    debug:
      var: http_response